name: Generate Failure Report

on:
  workflow_dispatch:

jobs:
  generate-report:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python pyth.py

      - name: Upload Generated Report
        uses: actions/upload-artifact@v4
        with:
          name: Irregular-Test-Failure-Report
          path: Irregular_Test_Failures.xlsx

      - name: Notify Teams
        shell: pwsh
        run: |
          $body = @{
            text = "Irregular Test Failure Report Generated. Repository: Excel_Report_Automation. Report: Irregular-Test-Failure-Report. Status: Success. Please download the report from the latest GitHub Actions run."
          } | ConvertTo-Json

          Invoke-RestMethod -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -ContentType "application/json" `
            -Body $body
